[package]
name = "session-code-lt"
version = "0.1.0"
edition = "2018"

[dependencies]
casper-contract = "1.4.4"
casper-types = "1.5.0"
num-traits = "0.2.15"

[[bin]]
name = "session-code-lt"
path = "bin/main.rs"
bench = false
doctest = false
test = false
